language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug 
